'use client'

import { useEffect, useMemo, useState } from 'react'
import { fraudnetApi } from '@/services/fraudnet-api'
import { Activity, AlertTriangle, ArrowUpRight, Ban, Bell, ChevronRight, CircleDollarSign, Cpu, FileSearch, Fingerprint, GitBranch, Globe2, LayoutDashboard, Menu, Network, Search, ShieldCheck, SlidersHorizontal, Sparkles, Users, X } from 'lucide-react'

type View = 'Overview' | 'Transactions' | 'Fraud Rings' | 'Investigation' | 'Model Performance' | 'Simulation'

const transactions = [
  { id: 'txn_8F29A1', customer: 'CUST-1042', amount: 18450, score: 98, status: 'Critical', signal: 'Shared device + coordinated timing', ring: 'FR-001' },
  { id: 'txn_8F28C7', customer: 'CUST-1091', amount: 17980, score: 96, status: 'Critical', signal: 'New IP + shared payment instrument', ring: 'FR-001' },
  { id: 'txn_8F27B4', customer: 'CUST-1138', amount: 18200, score: 94, status: 'High', signal: 'Amount anomaly + device cluster', ring: 'FR-001' },
  { id: 'txn_8F266D', customer: 'CUST-0877', amount: 8920, score: 81, status: 'High', signal: 'Velocity spike', ring: 'FR-002' },
  { id: 'txn_8F25E2', customer: 'CUST-1210', amount: 1240, score: 34, status: 'Monitor', signal: 'New device', ring: '—' },
]

const nav = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Transactions', icon: CircleDollarSign }, { label: 'Fraud Rings', icon: Network },
  { label: 'Investigation', icon: FileSearch }, { label: 'Model Performance', icon: Activity }, { label: 'Simulation', icon: SlidersHorizontal },
] as const

function RiskBadge({ status }: { status: string }) { return <span className={`risk risk-${status.toLowerCase()}`}><span className="risk-dot" />{status}</span> }
function Metric({ label, value, sub, icon: Icon, accent }: { label: string; value: string; sub: string; icon: typeof Activity; accent?: boolean }) { return <div className="metric-card"><div className="metric-top"><span>{label}</span><Icon size={17} /></div><strong className={accent ? 'accent-text' : ''}>{value}</strong><small>{sub}</small></div> }

export default function Page() {
  const [view, setView] = useState<View>('Overview')
  const [mobileOpen, setMobileOpen] = useState(false)
  const [selected, setSelected] = useState(transactions[0])
  const [simulated, setSimulated] = useState(false)
  const [query, setQuery] = useState('')
  const [apiSummary, setApiSummary] = useState<{ total_transactions: number; fraud_detected: number; fraud_rings: number; suspicious_amount: number } | null>(null)
  const [apiError, setApiError] = useState<string | null>(null)
  useEffect(() => {
    fraudnetApi.summary().then(setApiSummary).catch(() => setApiError('Backend unavailable — showing safe demo data.'))
  }, [])
  const visibleTransactions = useMemo(() => transactions.filter(t => `${t.id} ${t.customer} ${t.signal}`.toLowerCase().includes(query.toLowerCase())), [query])

  return <main className="app-shell">
    <aside className={`sidebar ${mobileOpen ? 'open' : ''}`}>
      <div className="brand"><div className="brand-mark"><ShieldCheck size={22} /></div><div><b>FRAUDNET</b><span>AI RISK MANAGER</span></div><button className="mobile-close" onClick={() => setMobileOpen(false)}><X size={18}/></button></div>
      <div className="workspace"><span className="live-dot"/> DEMO ENVIRONMENT <ChevronRight size={14}/></div>
      <nav>{nav.map(({ label, icon: Icon }) => <button key={label} className={view === label ? 'active' : ''} onClick={() => { setView(label); setMobileOpen(false) }}><Icon size={18}/><span>{label}</span>{label === 'Fraud Rings' && <em>3</em>}</button>)}</nav>
      <div className="sidebar-footer"><div className="security-note"><Fingerprint size={18}/><div><b>Protected workspace</b><span>Test data only</span></div></div><div className="user-row"><div className="avatar">AR</div><div><b>Alex Rao</b><span>Risk analyst</span></div><button><Bell size={16}/></button></div></div>
    </aside>
    {mobileOpen && <button className="scrim" onClick={() => setMobileOpen(false)} aria-label="Close menu"/>}
    <section className="content">
      <header className="topbar"><button className="mobile-menu" onClick={() => setMobileOpen(true)}><Menu size={20}/></button><div className="breadcrumb"><span>Workspace</span><ChevronRight size={14}/><b>{view}</b></div><div className="top-actions"><span className="status-pill"><span className="live-dot"/> Engine online</span><button className="icon-button"><Bell size={18}/><i/></button><div className="avatar small">AR</div></div></header>
      <div className="page-wrap">
        <div className="page-heading"><div><p className="eyebrow">THURSDAY, SEPTEMBER 3, 2026 <span>•</span> REAL-TIME MONITORING</p><h1>{view === 'Overview' ? 'Good morning, Alex.' : view}</h1><p className="subhead">{view === 'Overview' ? 'Here is what is happening across your payment network.' : view === 'Fraud Rings' ? 'Investigate coordinated networks before they scale.' : 'Explore signals and make confident risk decisions.'}</p></div><button className="primary-button" onClick={() => setView('Investigation')}><Sparkles size={16}/> Open investigator</button></div>
        {apiError && <div className="notice" role="status">{apiError}</div>}
        {view === 'Overview' && <Overview apiSummary={apiSummary} onSelect={(t) => { setSelected(t); setView('Investigation') }} />}
        {view === 'Transactions' && <Transactions query={query} setQuery={setQuery} visible={visibleTransactions} onSelect={(t) => { setSelected(t); setView('Investigation') }} />}
        {view === 'Fraud Rings' && <Rings onSelect={() => setView('Investigation')} />}
        {view === 'Investigation' && <Investigation transaction={selected} />}
        {view === 'Model Performance' && <ModelPerformance />}
        {view === 'Simulation' && <Simulation simulated={simulated} setSimulated={setSimulated} />}
      </div>
    </section>
  </main>
}

function Overview({ onSelect, apiSummary }: { onSelect: (t: typeof transactions[number]) => void; apiSummary?: { total_transactions: number } | null }) { return <>
  <div className="metrics-grid"><Metric label="TRANSACTIONS ANALYZED" value={apiSummary ? apiSummary.total_transactions.toLocaleString() : '48,291'} sub="↑ 12.4% from last period" icon={CircleDollarSign}/><Metric label="FRAUD DETECTED" value="1,284" sub="2.66% of total volume" icon={AlertTriangle} accent/><Metric label="ACTIVE FRAUD RINGS" value="3" sub="1 critical • 2 high risk" icon={Network} accent/><Metric label="SUSPICIOUS VALUE" value="₹2.84Cr" sub="↑ 8.1% flagged value" icon={ArrowUpRight}/></div>
  <div className="main-grid"><div className="panel chart-panel"><div className="panel-heading"><div><h2>Network risk activity</h2><p>Suspicious events detected over the last 14 days</p></div><button className="select-button">Last 14 days <ChevronRight size={14}/></button></div><div className="chart"><div className="chart-y"><span>120</span><span>80</span><span>40</span><span>0</span></div><div className="chart-area"><div className="grid-lines"/><svg viewBox="0 0 700 220" preserveAspectRatio="none" aria-label="Risk activity chart"><path d="M0,190 C40,180 40,155 85,165 S125,120 165,145 S210,170 250,118 S300,140 335,94 S380,126 415,88 S460,100 500,58 S550,88 585,44 S630,65 700,15" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M0,190 C40,180 40,155 85,165 S125,120 165,145 S210,170 250,118 S300,140 335,94 S380,126 415,88 S460,100 500,58 S550,88 585,44 S630,65 700,15 V220 H0Z" fill="currentColor" opacity=".08"/></svg><div className="chart-x"><span>Aug 21</span><span>Aug 25</span><span>Aug 29</span><span>Sep 03</span></div></div></div></div><div className="panel rings-panel"><div className="panel-heading"><div><h2>Priority investigations</h2><p>Ranked by composite risk score</p></div><button className="text-button">View all <ArrowUpRight size={14}/></button></div><div className="ring-list"><RingRow id="FR-001" title="Device cluster / Mumbai" score="98" severity="Critical" meta="11 customers • 4 devices"/><RingRow id="FR-002" title="IP velocity / Bengaluru" score="84" severity="High" meta="7 customers • 2 IPs"/><RingRow id="FR-003" title="Instrument sharing / Delhi" score="72" severity="High" meta="5 customers • 1 instrument"/></div></div></div>
  <div className="panel table-panel"><div className="panel-heading"><div><h2>Recent high-risk activity</h2><p>Transactions requiring analyst attention</p></div><button className="text-button">View transactions <ArrowUpRight size={14}/></button></div><TransactionTable rows={transactions.slice(0, 4)} onSelect={onSelect}/></div>
</> }
function RingRow({ id, title, score, severity, meta }: { id:string; title:string; score:string; severity:string; meta:string }) { return <div className="ring-row"><div className="ring-icon"><GitBranch size={16}/></div><div className="ring-info"><b>{id} <span>{title}</span></b><small>{meta}</small></div><div className="ring-score"><strong>{score}</strong><small>RISK SCORE</small></div><RiskBadge status={severity}/><ChevronRight size={16} className="muted"/></div> }
function TransactionTable({ rows, onSelect }: { rows: typeof transactions; onSelect: (t: typeof transactions[number]) => void }) { return <div className="table-scroll"><table><thead><tr><th>TRANSACTION</th><th>CUSTOMER</th><th>AMOUNT</th><th>RISK SCORE</th><th>PRIMARY SIGNAL</th><th>STATUS</th></tr></thead><tbody>{rows.map(t => <tr key={t.id} onClick={() => onSelect(t)}><td><b className="mono">{t.id}</b><small>{t.ring}</small></td><td className="mono">{t.customer}</td><td className="amount">₹{t.amount.toLocaleString('en-IN')}</td><td><span className="score">{t.score}</span></td><td>{t.signal}</td><td><RiskBadge status={t.status}/></td></tr>)}</tbody></table></div> }
function Transactions({ query, setQuery, visible, onSelect }: { query:string; setQuery:(x:string)=>void; visible:typeof transactions; onSelect:(t:typeof transactions[number])=>void }) { return <div className="panel table-panel"><div className="panel-heading"><div><h2>Transaction stream</h2><p>Showing scored transactions from the synthetic demo dataset</p></div><label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search transactions"/></label></div><TransactionTable rows={visible} onSelect={onSelect}/></div> }
function Rings({ onSelect }: { onSelect: () => void }) { return <div className="ring-cards">{[['FR-001','Coordinated device cluster','98','Critical','11 customers','4 devices','₹1.84L'],['FR-002','IP velocity network','84','High','7 customers','2 IPs','₹78,420'],['FR-003','Payment instrument sharing','72','High','5 customers','1 instrument','₹42,890']].map(r => <button className="ring-card" key={r[0]} onClick={onSelect}><div className="ring-card-top"><span className="ring-id">{r[0]}</span><RiskBadge status={r[3]}/></div><h2>{r[1]}</h2><div className="big-score">{r[2]}<small>/100 risk</small></div><div className="ring-card-meta"><span><Users size={14}/>{r[4]}</span><span><Cpu size={14}/>{r[5]}</span><span><CircleDollarSign size={14}/>{r[6]}</span></div><div className="evidence-bar"><span style={{width:`${Number(r[2])}%`}}/></div><div className="view-link">Investigate ring <ArrowUpRight size={14}/></div></button>)}</div> }
function Investigation({ transaction }: { transaction: typeof transactions[number] }) { return <div className="investigation-grid"><div className="panel evidence-panel"><div className="panel-heading"><div><p className="eyebrow">CASE FR-001 / TRANSACTION {transaction.id}</p><h2>Investigation workspace</h2><p>Composite decision generated from model and graph evidence.</p></div><RiskBadge status="Critical"/></div><div className="decision"><div className="decision-icon"><AlertTriangle size={22}/></div><div><span>RECOMMENDED ACTION</span><strong>Temporary restriction</strong><p>Hold transaction and review all connected accounts in FR-001.</p></div><span className="confidence">94% confidence</span></div><h3>Why this was flagged</h3><div className="evidence-list"><Evidence icon={Users} text="11 customers share the same device cluster" value="+28"/><Evidence icon={Globe2} text="6 transactions occurred within a 3-minute window" value="+22"/><Evidence icon={CircleDollarSign} text="Amount is 7.2× customer's normal average" value="+18"/><Evidence icon={Fingerprint} text="Connected account has previous fraud history" value="+16"/></div></div><div className="panel graph-panel"><div className="panel-heading"><div><h2>Entity network</h2><p>Explainable relationship view</p></div><button className="icon-button"><Search size={16}/></button></div><div className="network"><div className="network-line l1"/><div className="network-line l2"/><div className="network-line l3"/><div className="node transaction">T<br/><small>txn_8F29</small></div><div className="node customer c1">C<small>CUST-1042</small></div><div className="node customer c2">C<small>CUST-1091</small></div><div className="node device">D<small>DEV-77A</small></div><div className="node ip">IP<small>103.24.x</small></div><div className="network-legend"><span><i className="dot customer-dot"/>Customer</span><span><i className="dot device-dot"/>Device</span><span><i className="dot ip-dot"/>IP address</span></div></div></div></div> }
function Evidence({ icon: Icon, text, value }: { icon: typeof Users; text:string; value:string }) { return <div className="evidence"><div className="evidence-icon"><Icon size={16}/></div><span>{text}</span><b>{value}</b></div> }
function ModelPerformance() { return <div className="performance"><div className="metrics-grid"><Metric label="PRECISION" value="0.93" sub="93% of alerts were relevant" icon={TargetIcon}/><Metric label="RECALL" value="0.89" sub="89% of fraud found" icon={Search}/><Metric label="F1 SCORE" value="0.91" sub="Balanced test-set score" icon={Activity} accent/><Metric label="ROC-AUC" value="0.96" sub="Held-out test set" icon={GitBranch}/></div><div className="panel confusion"><div className="panel-heading"><div><h2>Model evaluation</h2><p>Random Forest • held-out synthetic test set • n=2,000</p></div><span className="model-tag">v1.0.0</span></div><div className="confusion-body"><div className="matrix"><span/><b>Predicted legit</b><b>Predicted fraud</b><b>Actual legit</b><strong>1,796</strong><strong className="warn">104</strong><b>Actual fraud</b><strong className="warn">73</strong><strong className="good">27</strong></div><div className="model-copy"><h3>What this means</h3><p><b>Precision</b> keeps analyst workload focused by limiting false alarms.</p><p><b>Recall</b> helps surface more of the coordinated fraud that individual rules miss.</p><p className="muted-copy">Metrics are generated by the local training pipeline and are for demo evaluation only.</p></div></div></div></div> }
function TargetIcon(props: {size?:number}) { return <CrosshairIcon {...props}/> } function CrosshairIcon({size=18}: {size?:number}) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3"/></svg> }
function Simulation({ simulated, setSimulated }: { simulated:boolean; setSimulated:(x:boolean)=>void }) { return <div className="simulation-grid"><div className="panel sim-form"><p className="eyebrow">DEFENSIVE WHAT-IF TOOL</p><h2>Block a device</h2><p>Estimate the blast radius of restricting an entity. This is a simulation only and does not affect live payments.</p><label>Device ID<input defaultValue="DEV-77A" aria-label="Device ID"/></label><button className="primary-button" onClick={()=>setSimulated(true)}><Ban size={16}/> Run simulation</button></div><div className="panel sim-result">{simulated ? <><div className="result-head"><div className="success-icon"><ShieldCheck size={20}/></div><div><span>SIMULATION COMPLETE</span><h2>DEV-77A restriction impact</h2></div></div><div className="result-grid"><div><strong>11</strong><span>Affected accounts</span></div><div><strong>37</strong><span>Affected transactions</span></div><div><strong>₹4.28L</strong><span>Transaction value</span></div><div><strong className="accent-text">82%</strong><span>Estimated risk reduction</span></div></div><div className="notice"><AlertTriangle size={17}/><span>Estimate based on historical relationships in the demo dataset. No real payment action was taken.</span></div></> : <div className="empty"><SlidersHorizontal size={25}/><h3>Ready to simulate</h3><p>Enter an entity and run a defensive impact assessment.</p></div>}</div></div> }

